### ISSUE TITLE
TTS Doesn't work

### ISSUE THREAD

**Issue by Vinny5353** [Weilbyte/tiktok-tts#7] opened 2022-08-22 14:00 UTC
![image](https://user-images.githubusercontent.com/98285923/185939330-aa98f41f-7500-4cb0-a702-e28ce27853ad.png)

**Comment by Kabir-k** [comment] 2022-08-22 17:00
Not working

**Comment by Weilbyte** [comment] 2022-09-05 15:47
Duplicate of #10

**Closed by Weilbyte** 2022-09-05 15:47 UTC
