### ISSUE TITLE
Can t use tts

### ISSUE THREAD

**Issue by Lfkedyn77** [Weilbyte/tiktok-tts#6] opened 2022-08-22 11:00 UTC
I try to make a tiktok video but i can t, the site isn t working

**Comment by Petter1515** [comment] 2022-08-22 11:46
![image](https://user-images.githubusercontent.com/109671200/185913823-fbc92f43-6b90-47aa-852b-0ab8c985f877.png)

The site has an error @Weilbyte :(

**Comment by Weilbyte** [comment] 2022-08-22 12:48
Will take a look soon

**Comment by Kabir-k** [comment] 2022-08-22 16:57
Tiktok tts is not working

**Comment by Kabir-k** [comment] 2022-08-22 16:57
![Screenshot_20220822-222739](https://user-images.githubusercontent.com/97743706/185977193-e3549520-26f0-440f-998e-60e6acf2c5ec.png)

**Comment by Weilbyte** [comment] 2022-09-05 15:47
Duplicate of #10

**Closed by Weilbyte** 2022-09-05 15:47 UTC
