### ISSUE TITLE
Couldn't load speech

### ISSUE THREAD

**Issue by MutantRhino4524** [Weilbyte/tiktok-tts#11] opened 2022-09-03 13:56 UTC
Server returned error (message: "Couldn't load speech. Try again.").

**Comment by chrisbt1213** [comment] 2022-09-05 15:09
Encountering the same issue using GoogleChrome - Version 104.0.5112.101 (Official Build) (x86_64) on MacOS

**Comment by Weilbyte** [comment] 2022-09-05 15:46
Duplicate of #10

**Closed by Weilbyte** 2022-09-05 15:46 UTC
